# Change baseurl before deploy
baseurl = "https://w2343419-del.github.io/WangScape/"
languageCode = "en-us"
title = "WangScape"

defaultContentLanguage = "zh-cn"

hasCJKLanguage = true

[pagination]
pagerSize = 3
disableAliases = false
path = 'page'

[minify]
  disableXML = true
  minifyOutput = true

