# English-specific parameters
mainSections = ["post"]
rssFullContent = true
favicon = "/favicon.png"

[sidebar]
    emoji = ""
    subtitle = "Waiting for flowers when leaving, arriving when spring is gone."
[sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"

[article]
    readingTime = true
    license.enabled = false
    math = true
    toc = true

[colorScheme]
    toggle = true
    default = "auto"

# ===== Right sidebar widgets =====
[[widgets.homepage]]
    type = "search"

[[widgets.homepage]]
    type = "archives"
    [widgets.homepage.params]
        limit = 5

[[widgets.homepage]]
    type = "categories"
    [widgets.homepage.params]
        limit = 10

[[widgets.homepage]]
    type = "tag-cloud"
    [widgets.homepage.params]
        limit = 20

# ===== Article page widgets =====
[[widgets.page]]
    type = "toc"

[[widgets.page]]
    type = "categories"

[[widgets.page]]
    type = "tag-cloud"
    [widgets.page.params]
        limit = 20

        [[widgets.homepage.params.items]]
            name = "Google"
            url = "https://google.com"
            desc = "Popular search engine"
