# 中文特定参数
mainSections = ["post"]
rssFullContent = true
favicon = "/favicon.png"

[sidebar]
    emoji = ""
    subtitle = "偏我去时花满楼，偏我来时不逢春。"
[sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"

[article]
    readingTime = true
    license.enabled = false
    math = true
    toc = true

[colorScheme]
    toggle = true
    default = "auto"

# ===== 右侧栏小部件 =====
[[widgets.homepage]]
    type = "search"

[[widgets.homepage]]
    type = "archives"
    [widgets.homepage.params]
        limit = 5

[[widgets.homepage]]
    type = "categories"
    [widgets.homepage.params]
        limit = 10

[[widgets.homepage]]
    type = "tag-cloud"
    [widgets.homepage.params]
        limit = 20

# ===== 文章页面小部件 =====
[[widgets.page]]
    type = "toc"

[[widgets.page]]
    type = "categories"

[[widgets.page]]
    type = "tag-cloud"
    [widgets.page.params]
        limit = 20
